spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
      - id: products_path
        uri: lb://ecommerce-products
        predicates:
        - Path=/products/**
      - id: customers_path
        uri: lb://ecommerce-customers
        predicates:
        - Path=/customers/**
      - id: orders_path
        uri: lb://ecommerce-orders
        predicates:
        - Path=/orders/**
eureka:
  client:
    service-url: http://discovery-server:8761/eureka                                 
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - metrics
server:
  port: 8000